/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import BaseDatos.BD;
import Clases.Lista;
import java.awt.Color;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author MHC <miguel.hrc>
 */
public class FrmBusquedaLista extends javax.swing.JDialog {

    /**
     * Creates new form FrmBusquedaLista
     */
    public FrmBusquedaLista(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.lightGray);
    }

    String Carrera;
    String Grupo;
    String Semestre;
    String Materia;
    String url;
    public String ID = "";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JCmbCarrera = new javax.swing.JComboBox<>();
        JCmbSemestre = new javax.swing.JComboBox<>();
        JCmbGrupo = new javax.swing.JComboBox<>();
        jLblCarrera = new javax.swing.JLabel();
        jLblSemestre = new javax.swing.JLabel();
        jLblGrupo = new javax.swing.JLabel();
        jLblMateria = new javax.swing.JLabel();
        JCmbMateria = new javax.swing.JComboBox<>();
        jBtnAceptar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        JCmbCarrera.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        JCmbCarrera.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JCmbCarreraFocusGained(evt);
            }
        });
        JCmbCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCmbCarreraActionPerformed(evt);
            }
        });

        JCmbSemestre.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        JCmbSemestre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JCmbSemestreFocusGained(evt);
            }
        });
        JCmbSemestre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCmbSemestreActionPerformed(evt);
            }
        });

        JCmbGrupo.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        JCmbGrupo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JCmbGrupoFocusGained(evt);
            }
        });
        JCmbGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCmbGrupoActionPerformed(evt);
            }
        });

        jLblCarrera.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLblCarrera.setText("Carrera");

        jLblSemestre.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLblSemestre.setText("Semestre");

        jLblGrupo.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLblGrupo.setText("Grupo");

        jLblMateria.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLblMateria.setText("Materia");

        JCmbMateria.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        JCmbMateria.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JCmbMateriaFocusGained(evt);
            }
        });
        JCmbMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCmbMateriaActionPerformed(evt);
            }
        });

        jBtnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png/24x24/accept.png"))); // NOI18N
        jBtnAceptar.setText("Aceptar");
        jBtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAceptarActionPerformed(evt);
            }
        });

        jMenuBar1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "L'S.SOFT", javax.swing.border.TitledBorder.TRAILING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLblMateria))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JCmbMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JCmbCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblCarrera))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblSemestre)
                    .addComponent(JCmbSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JCmbGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnAceptar))
                    .addComponent(jLblGrupo))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblMateria)
                    .addComponent(jLblCarrera)
                    .addComponent(jLblSemestre)
                    .addComponent(jLblGrupo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JCmbMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JCmbSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JCmbGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JCmbCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnAceptar))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JCmbCarreraFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JCmbCarreraFocusGained
        // TODO add your handling code here:
        BD mBD = new BD();
        this.JCmbCarrera.removeAllItems();
        this.JCmbSemestre.removeAllItems();
        this.JCmbGrupo.removeAllItems();

        try {
            List<Lista> mLista = mBD.consultarListaCarrera(String.valueOf(this.JCmbMateria.getSelectedItem()));
            for (Lista actual : mLista) {
                this.JCmbCarrera.addItem(actual.getCarrera());
            }
        } catch (SQLException ex) {
            Logger.getLogger(FrmBusquedaLista.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JCmbCarreraFocusGained

    private void JCmbCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCmbCarreraActionPerformed
        // TODO add your handling code here:
        Carrera = String.valueOf(this.JCmbCarrera.getSelectedItem());
        System.out.println("Carrera: " + Carrera + "\n");
    }//GEN-LAST:event_JCmbCarreraActionPerformed

    private void JCmbSemestreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JCmbSemestreFocusGained
        // TODO add your handling code here:
        BD mBD = new BD();
        this.JCmbSemestre.removeAllItems();
        try {
            List<Lista> mLista = mBD.consultarListaSemestres(String.valueOf(this.JCmbMateria.getSelectedItem()), String.valueOf(this.JCmbCarrera.getSelectedItem()));
            for (Lista actual : mLista) {
                this.JCmbSemestre.addItem(String.valueOf(actual.getSemestre()));
            }
        } catch (SQLException ex) {
            Logger.getLogger(FrmBusquedaLista.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JCmbSemestreFocusGained

    private void JCmbSemestreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCmbSemestreActionPerformed
        // TODO add your handling code here:
        Semestre = String.valueOf(this.JCmbSemestre.getSelectedItem());
        System.out.println("Semestre: " + Semestre + "\n");
    }//GEN-LAST:event_JCmbSemestreActionPerformed

    private void JCmbGrupoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JCmbGrupoFocusGained
        // TODO add your handling code here:
        BD mBD = new BD();
        this.JCmbGrupo.removeAllItems();
        try {
            List<Lista> mLista = mBD.consultarListaGrupo(String.valueOf(this.JCmbMateria.getSelectedItem()), String.valueOf(this.JCmbCarrera.getSelectedItem()), Semestre);
            for (Lista actual : mLista) {
                this.JCmbGrupo.addItem(String.valueOf(actual.getGrupo()));
            }
        } catch (SQLException ex) {
            Logger.getLogger(FrmBusquedaLista.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JCmbGrupoFocusGained

    private void JCmbGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCmbGrupoActionPerformed
        // TODO add your handling code here:
        Grupo = String.valueOf(this.JCmbGrupo.getSelectedItem());
        System.out.println("Grupo: " + Grupo + "\n");
    }//GEN-LAST:event_JCmbGrupoActionPerformed

    private void JCmbMateriaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JCmbMateriaFocusGained
        // TODO add your handling code here:
        BD mBD = new BD();
        this.JCmbMateria.removeAllItems();
        this.JCmbCarrera.removeAllItems();
        this.JCmbSemestre.removeAllItems();
        this.JCmbGrupo.removeAllItems();
        try {
            List<Lista> mLista = mBD.consultarListaMateria();
            for (Lista actual : mLista) {
                this.JCmbMateria.addItem(actual.getMateria());
            }
        } catch (SQLException ex) {
            Logger.getLogger(FrmBusquedaLista.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JCmbMateriaFocusGained

    private void JCmbMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCmbMateriaActionPerformed
        // TODO add your handling code here:
        Materia = String.valueOf(this.JCmbMateria.getSelectedItem());
        System.out.println("Materia: " + Materia + "\n");
    }//GEN-LAST:event_JCmbMateriaActionPerformed

    private void jBtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAceptarActionPerformed
        // TODO add your handling code here:
        if (((this.JCmbMateria.getItemCount() == 0) | (this.JCmbCarrera.getItemCount() == 0) | (this.JCmbSemestre.getItemCount() == 0) | (this.JCmbGrupo.getItemCount() == 0))) {
            JOptionPane.showMessageDialog(rootPane, "Existen campos vacios. \nLlene todos los campos");
            setVisible(true);
        } else {
            try {
                BD mBD = new BD();
                String ID = "0";
                List<Lista> mLista = mBD.consultarListarID(Materia, Carrera, Grupo, Semestre);
                for (Lista actual : mLista) {
                    ID = String.valueOf(actual.getIdLista());
                }
                setVisible(false);
                System.out.println("id =" + ID);

                JFileChooser dato = new JFileChooser();
                FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos csv", "csv");
                dato.setAcceptAllFileFilterUsed(false);
                dato.setFileFilter(filter);
                int op = dato.showOpenDialog(this);
                if (op == JFileChooser.APPROVE_OPTION) {
                    url = dato.getSelectedFile().getPath();
                }

                if ("".equals(url)) {
                    JOptionPane.showMessageDialog(rootPane, "Seleccione un archivo");
                } else {
                    System.out.println(url);

                    try {
                        mBD.Cargar(ID, url);
                        JOptionPane.showMessageDialog(rootPane, "Archivo cargado");
                    } catch (SQLException ex) {
                        Logger.getLogger(FrmBusquedaLista.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }

            } catch (SQLException ex) {
                Logger.getLogger(FrmBusquedaLista.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jBtnAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmBusquedaLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmBusquedaLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmBusquedaLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmBusquedaLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmBusquedaLista dialog = new FrmBusquedaLista(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JCmbCarrera;
    private javax.swing.JComboBox<String> JCmbGrupo;
    private javax.swing.JComboBox<String> JCmbMateria;
    private javax.swing.JComboBox<String> JCmbSemestre;
    private javax.swing.JButton jBtnAceptar;
    private javax.swing.JLabel jLblCarrera;
    private javax.swing.JLabel jLblGrupo;
    private javax.swing.JLabel jLblMateria;
    private javax.swing.JLabel jLblSemestre;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
